package jlo.ioe.data

/**
 *
 * @author  jlowens
 */
class EmailPanel extends jlo.ioe.ui.Panel {
  initComponents();
  preferredSize(500,500)
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private def initComponents() = {
    jLabel1 = new jlo.ioe.ui.Label("To:")
    jLabel2 = new jlo.ioe.ui.Label("Cc:")
    jLabel3 = new jlo.ioe.ui.Label("Subject:")
    toField = new jlo.ioe.ui.TextField with jlo.ioe.ui.behavior.DocumentTracker {}
    ccField = new jlo.ioe.ui.TextField 
    subjectField = new jlo.ioe.ui.TextField
    jScrollPane1 = new jlo.ioe.ui.Scroller(null)
    bodyField = new jlo.ioe.ui.TextPane
    jButton1 = new jlo.ioe.ui.Button("Attach...")

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    
    ccField.addActionListener(new java.awt.event.ActionListener() {
      def actionPerformed(evt:java.awt.event.ActionEvent) {
        ccFieldActionPerformed(evt);
      }
    });
    
    jScrollPane1.setViewportView(bodyField);
        
    val layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
           .addContainerGap()
           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 421, scala.compat.Math.MAX_SHORT)
                .add(layout.createSequentialGroup()
                     .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                          .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, scala.compat.Math.MAX_SHORT)
                          .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, scala.compat.Math.MAX_SHORT)
                          .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, scala.compat.Math.MAX_SHORT))
                     .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                     .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                          .add(toField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, scala.compat.Math.MAX_SHORT)
                          .add(ccField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, scala.compat.Math.MAX_SHORT)
                          .add(subjectField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, scala.compat.Math.MAX_SHORT)))
                .add(org.jdesktop.layout.GroupLayout.LEADING, jButton1))
           .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
           .addContainerGap()
           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(toField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
           .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel2)
                .add(ccField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
           .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel3)
                .add(subjectField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
           .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
           .add(jButton1)
           .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
           .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, scala.compat.Math.MAX_SHORT)
           .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private def ccFieldActionPerformed(evt:java.awt.event.ActionEvent) = {//GEN-FIRST:event_ccFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ccFieldActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  var bodyField:javax.swing.JEditorPane = _
  var ccField:javax.swing.JTextField = _
  var jButton1:javax.swing.JButton = _
  var jLabel1:javax.swing.JLabel = _
  var jLabel2: javax.swing.JLabel = _
  var jLabel3 : javax.swing.JLabel = _
  var jScrollPane1 : javax.swing.JScrollPane = _
  var subjectField : javax.swing.JTextField = _
  var toField : jlo.ioe.ui.TextField = _
  // End of variables declaration//GEN-END:variables


}
